### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by Hellengo** [thyrlian/jooi#2]
hi,run
set -o pipefail
infer -i -- xcodebuild -workspace Vodka.xcworkspace -scheme Vodka -configuration Debug -sdk iphoneos | ruby junit_output_of_infer.rb ${WORKSPACE}/infer_junit_results.xml

.......
.......
*\* CLEAN SUCCEEDED **

junit_output_of_infer.rb:10: syntax error, unexpected &, expecting ')'
      !(@file &amp;&amp; @filename &amp;&amp; @li...
                    ^
junit_output_of_infer.rb:10: syntax error, unexpected &, expecting ')'
...ile &amp;&amp; @filename &amp;&amp; @line &amp;&amp; @sort &...
...                               ^
junit_output_of_infer.rb:10: syntax error, unexpected &, expecting ')'
...ilename &amp;&amp; @line &amp;&amp; @sort &amp;&amp; @type &...
...                               ^
junit_output_of_infer.rb:10: syntax error, unexpected &, expecting ')'
...; @line &amp;&amp; @sort &amp;&amp; @type &amp;&amp; @detail...
...                               ^
junit_output_of_infer.rb:10: syntax error, unexpected &, expecting ')'
...; @sort &amp;&amp; @type &amp;&amp; @details).nil?
...                               ^
junit_output_of_infer.rb:18: syntax error, unexpected &
    class &lt;&lt; self
           ^
junit_output_of_infer.rb:18: syntax error, unexpected &, expecting keyword_end
    class &lt;&lt; self
               ^
junit_output_of_infer.rb:37: syntax error, unexpected &
...       if !issues.empty? &amp;&amp; !issues.last.file.nil? &...
...                               ^
junit_output_of_infer.rb:37: syntax error, unexpected &, expecting keyword_end
...; !issues.last.file.nil? &amp;&amp; issues.last.details.nil?...
...                               ^
junit_output_of_infer.rb:37: syntax error, unexpected &, expecting keyword_end
...issues.last.details.nil? &amp;&amp; !details.empty?
...                               ^
junit_output_of_infer.rb:48: syntax error, unexpected &
    class &lt;&lt; self
           ^
junit_output_of_infer.rb:48: syntax error, unexpected &, expecting keyword_end
    class &lt;&lt; self
               ^
junit_output_of_infer.rb:52: syntax error, unexpected '=', expecting ')'
...          xml.testsuite(:name =&gt; 'Infer', :tests =&gt; is...
...                               ^
junit_output_of_infer.rb:52: syntax error, unexpected ',', expecting keyword_end
....testsuite(:name =&gt; 'Infer', :tests =&gt; issues.size, :f...
...                               ^
junit_output_of_infer.rb:52: syntax error, unexpected '=', expecting :: or '[' or '.'
... =&gt; issues.size, :failures =&gt; issues.size) {
...                               ^
junit_output_of_infer.rb:52: syntax error, unexpected ')', expecting keyword_end
...e, :failures =&gt; issues.size) {
...                               ^
junit_output_of_infer.rb:55: syntax error, unexpected '=', expecting ')'
...           xml.testcase(:name =&gt; "#{issue.filename}:#{iss...
...                               ^
junit_output_of_infer.rb:55: syntax error, unexpected ')', expecting keyword_end
...issue.filename}:#{issue.line}") {
...                               ^
junit_output_of_infer.rb:56: syntax error, unexpected '=', expecting ')'
...            xml.failure(:type =&gt; issue.type, :message =&g...
...                               ^
junit_output_of_infer.rb:56: syntax error, unexpected '=', expecting :: or '[' or '.'
...pe =&gt; issue.type, :message =&gt; issue.details)
...                               ^
junit_output_of_infer.rb:56: syntax error, unexpected ')', expecting keyword_end
junit_output_of_infer.rb:64: syntax error, unexpected '=', expecting ')'
...          xml.testsuite(:name =&gt; 'Infer', :tests =&gt; '1...
...                               ^
junit_output_of_infer.rb:64: syntax error, unexpected ',', expecting keyword_end
....testsuite(:name =&gt; 'Infer', :tests =&gt; '1', :errors =&...
...                               ^
junit_output_of_infer.rb:64: syntax error, unexpected ',', expecting keyword_end
...&gt; 'Infer', :tests =&gt; '1', :errors =&gt; 0, :skipped =&...
...                               ^
junit_output_of_infer.rb:64: syntax error, unexpected ',', expecting keyword_end
...sts =&gt; '1', :errors =&gt; 0, :skipped =&gt; 0, :failures ...
...                               ^
junit_output_of_infer.rb:64: syntax error, unexpected ',', expecting keyword_end
...rors =&gt; 0, :skipped =&gt; 0, :failures =&gt; 0)
...                               ^
junit_output_of_infer.rb:64: syntax error, unexpected ')', expecting keyword_end
junit_output_of_infer.rb:86: syntax error, unexpected end-of-input, expecting keyword_end

  ^
Fatal error: exception Sys_error("Broken pipe")
Traceback (most recent call last):
  File "/usr/local/bin/infer", line 178, in <module>
    main()
  File "/usr/local/bin/infer", line 164, in main
    analysis.analyze_and_report()
  File "/usr/local/Cellar/infer/0.8.0/libexec/infer/lib/python/inferlib/analyze.py", line 481, in analyze_and_report
    if self.analyze() == os.EX_OK:
  File "/usr/local/Cellar/infer/0.8.0/libexec/infer/lib/python/inferlib/analyze.py", line 381, in analyze
    self.args.analyzer
  File "/usr/local/Cellar/infer/0.8.0/libexec/infer/lib/python/inferlib/analyze.py", line 218, in run_command
    raise e
subprocess.CalledProcessError: Command '[u'/usr/local/Cellar/infer/0.8.0/libexec/infer/lib/python/inferlib/../../../bin/InferAnalyze', u'-results_dir', u'/Users/speedxserver/.jenkins/jobs/StaticAnalysis_For_iOS/workspace/infer-out', u'-makefile', u'Makefile', u'-allow_specs_cleanup', u'-inferconfig_home', '/Users/speedxserver/.jenkins/jobs/StaticAnalysis_For_iOS/workspace', u'-models', u'/usr/local/Cellar/infer/0.8.0/libexec/infer/lib/python/inferlib/../../../lib/java/models.jar', u'-reactive', u'-project_root', '/Users/speedxserver/.jenkins/jobs/StaticAnalysis_For_iOS/workspace']' returned non-zero exit status 2
Build step 'Execute shell' marked build as failure
Archiving artifacts
Recording test results
ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?
No emails were triggered.
Finished: FAILURE

**Comment by thyrlian** [comment]
Hi @Hellengo 

I had a look at the logs.  It seems like the input of jooi (which is the output of Facebook Infer) is wrong.  So I think you should make sure that Infer could run through successfully first :)

The error begins from these lines:

``` bash
Fatal error: exception Sys_error("Broken pipe")
Traceback (most recent call last):
File "/usr/local/bin/infer", line 178, in 
main()
File "/usr/local/bin/infer", line 164, in main
analysis.analyze_and_report()
File "/usr/local/Cellar/infer/0.8.0/libexec/infer/lib/python/inferlib/analyze.py", line 481, in analyze_and_report
if self.analyze() == os.EX_OK:
```

Thanks and hope you could get it work.

**Comment by Hellengo** [comment]
if run
infer -i -- xcodebuild -workspace Vodka.xcworkspace -scheme Vodka -configuration Debug -sdk iphoneos
only，

build successed。

Summary of the reports

  DIRECT_ATOMIC_PROPERTY_ACCESS: 357
     PARAMETER_NOT_NULL_CHECKED: 53
                    MEMORY_LEAK: 14
               NULL_DEREFERENCE: 11
         BAD_POINTER_COMPARISON: 7
        STRONG_DELEGATE_WARNING: 5
          IVAR_NOT_NULL_CHECKED: 3
                   RETAIN_CYCLE: 2
Archiving artifacts
Finished: SUCCESS
