### ISSUE TITLE
Problem running example

### ISSUE THREAD

**Issue by dbarwacz** [thyrlian/jooi#3]
I installed jooi and try to run it with fastlane like this:

```
infer -- ./gradlew compileInternalDebugSources | ruby junit_output_of_infer.rb $PWD/infer_junit_results.xml
```

Instead I get 

```
ruby: No such file or directory -- junit_output_of_infer.rb (LoadError)
```

I guess it might be ruby-related but it would be great if I could get confirmation/help fixing setup.

**Comment by dbarwacz** [comment]
Ok, my fault, I stupidly expected ruby to fetch required script automtically (like gradle usually does). I would add a note for other though.

**Comment by thyrlian** [comment]
Good to know that it works for you :)
